### ISSUE TITLE
How to point VortexGate to arbitrary networks or contract addresses (no truffle, no embark)

### ISSUE THREAD

**Issue by chapati23** [Horyus/vortex-components#1]
Hey,
we don't have truffle or embark integrated into our UI. instead we import the ABIs of our contracts from an npm module. so essentially, i'm wondering how to tell `VortexGate` either what network to search for my contract _or_ how to pass a contract address directly.

Couldn't find that in the docs, unless i'm blind…

**Comment by mortimr** [comment]
Hi chapati23 ,

No you're not blind, currently `Vortex` (and by extension `VortexGate`) on support `truffle` or `embark` types. But you are right, all I need is the ABI.

I will work on a `manual` type for the next version. What would you say about this ?
```js
{
    type: 'manual',
    manual_contracts: {
        SimpleStorage: {
            abi: <your contract ABI>,

            at: "0x...", 

            deployed_bytecode: "0x..."
        }
    }
}
```

`deployed_bytecode` + `at` allows me to check if the contract is present on the current network.

If no `at` is given, then no preloading is done (you will be able to manually load your contract afterwards)

If not `deployed_bytecode` is given, then no network checks will be done.

Does it seem ok to you ?

You can track the ticket on gitlab : https://gitlab.com/Horyus/vortex/vortex/issues/54

**Comment by chapati23** [comment]
That would be exactly what I was looking for :)

**Comment by mortimr** [comment]
Hi again @chapati23 !

The new contract configuration type `manual` is now on the latest version of the npm module [`vort_x@1.0.0-charlie`](https://www.npmjs.com/package/vort_x) package !

You can find some usage details at https://vort-x.readthedocs.io/en/develop/react/#vortexgate.

I'd love to get your feedback on this :)

**Comment by chapati23** [comment]
looks nice but doesn't work for me unfortunately. always getting `Gatelock: You need to provide VortexWeb3Loading, VortexWeb3Loaded, VortexWeb3LoadError, VortexWeb3NetworkError and VortexWeb3Locked as unique children of VortexGate`

my component now looks like this:

```js
      {typeof window !== 'undefined' && (
        <VortexGate
          contracts={{
            type: 'manual',
            manual_contracts: {
              BrickblockToken: {
                abi: BrickblockToken,
                at: '0x4a6058666cf1057eaC3CD3A5a614620547559fc9'
              }
            }
          }}
          loader={VortexMetamaskLoader(Web3)}
          network_contracts={[BrickblockToken]}
        >
          <VortexWeb3Loading>loading…</VortexWeb3Loading>
          <br />
          <VortexWeb3Loaded>Web3 Loaded!</VortexWeb3Loaded>
          <br />
          <VortexWeb3LoadError>web3 load error</VortexWeb3LoadError>
          <br />
          <VortexWeb3NetworkError>web3 network error</VortexWeb3NetworkError>
          <br />
          <VortexWeb3Locked>web3 locked</VortexWeb3Locked>
        </VortexGate>
      )}
```

what am i missing?

**Comment by mortimr** [comment]
Hey, 
you actually need to provide only the 5 required components as children (`VortexWeb3Loading, VortexWeb3Loaded, VortexWeb3LoadError, VortexWeb3NetworkError and VortexWeb3Locked`).

I am checking if the number of children is 5, and I take each one of them separately and check if I have one of each type. After that, only one of the 5 components will get rendered.

Also, looking at how you instantiate the `VortexGate`, I see that :
- You are using `network_contracts` with `manual` type. this argument is only useful for `truffle` configuration and will be moved inside the `truffle` configuration soon.
- You are giving the same argument to the `abi` of your contract and to the `network_contract`, you should be sure to give the correct abi to the `manual` configuration (one easy way to check if it would work is simply by trying to create and [`web3.eth.Contract`](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html) instance of your contract with the desired abi, because it is what I am doing behind the scenes)

So, your code should look like this:

```jsx
{typeof window !== 'undefined' && (
        <VortexGate
          contracts={{
            type: 'manual',
            manual_contracts: {
              BrickblockToken: {
                abi: BrickblockTokenABI,
                at: '0x4a6058666cf1057eaC3CD3A5a614620547559fc9'
              }
            }
          }}
          loader={VortexMetamaskLoader(Web3)}
        >
          <VortexWeb3Loading>loading…</VortexWeb3Loading>

          <VortexWeb3Loaded>Web3 Loaded!</VortexWeb3Loaded>

          <VortexWeb3LoadError>web3 load error</VortexWeb3LoadError>

          <VortexWeb3NetworkError>web3 network error</VortexWeb3NetworkError>

          <VortexWeb3Locked>web3 locked</VortexWeb3Locked>
        </VortexGate>
      )}
```
- Remove the `<br />` as there is no point in having components between the 5 Vortex indexers (and it prevents `VortexGate` from properly loading)
- Remove the `network_contracts` argument as it is useful for `truffle` and will be moved soon
- Be sure you give a correct `ABI` to your `manual` configuration

**Comment by chapati23** [comment]
aaah, i see 👀 https://github.com/Horyus/vortex-components/blob/285b86d73301571fb3e92ffa157cef741f1c13ee/src/components/vortex-components/vortex-gate/gatelock.jsx#L8

isn't that a bit too strict as an api? checking whether the children you expect are present (instead of forbidding all children _except_ the vortex ones) would make this component much more flexible.

**Comment by mortimr** [comment]
What is happening is the following:
- Check if amount of children makes sense (if not 5, then I know you can't possibly handle all status types)
- Iterate over the 5 children and check if I have one of each type (and no duplicate), store them separately
- Render only one of the 5 children, depending on current Web3 Status

It would make no sense to allow other components between the vortex ones as I am not rendering all my children, only one at a time.

Something I could do is to check if `children.length` is `<= 5`, but still check for my vortex components. And again, what should I do if the current status is one you are not providing ? 

- Should I render nothing ? That's not very intuitive, the dev won't know what is happening. 
- Throw an error ? That would be the exact same situation as now.
- Render a custom message ? That's not the role I saw for the `VortexGate`, as it was intended to create a branching system based on web3 status, that would take as input your custom components.

Also I don't see why someone should not use all the vortex components, they're here to enhance UX by allowing you to transmit errors to your users way more easily, and guide them towards the `VortexLoaded` component.


`VortexWeb3Loading`: "Wait a bit, things are happening behind the scene, don't worry"
`VortexWeb3LoadError`: "Oh looks like I can't load web3, are you sure Metamask is properly installed ?"
`VortexWeb3NetworkError`: "You are not on the good network to use my app, I currently have not deployed my contracts to this network, you should switch to XXXXX network"
`VortexWeb3Locked`: "Unlock your Metamask !"
`VortexWeb3Loaded`: "All good, you can use my app now !"

And I think that's the kind of messages/guidance a user needs on every Dapp (especially newbies).

It's better than UI glitches and console errors, right x) ?

**Comment by chapati23** [comment]
hmm then maybe i intuitively misunderstood the `VortexGate`. i thought of it as kind of like a container-wrapper that i'd just wrap around every react component that needs blockchain data.

but there are also components that don't rely on blockchain data. for example, title components you'd always wanna display, regardless of web3 states.

**Comment by mortimr** [comment]
I built it in order to have your whole Blockchain App inside the `VortexWeb3Loaded` component.
I see what you are looking for. You want to be able to have areas connected to Ethereum that would change locally depending on Web3 status.

This is a use case it didn't thinked of, for me a Web3 error meant total unusability of the application.

This is something I could add. Have a separate way of using Vortex, with a simple Provider that you can place at the top of your app, that will render children no matter what, and lighter versions of the `VortexGate` that can be found multiple times inside your app.

Also if this is what you are trying to achieve, you can manually instantiate `Vortex` like in the `VortexGate` constructor, and have your own components connected to redux on `state.web3.status` (that's how I do it).

**Comment by chapati23** [comment]
Gotcha, then it was just a misunderstanding on my part about the API. Expectation management is hard :)
